"""Add age column to User

Revision ID: 4fc14db5f248
Revises: 
Create Date: 2025-09-19 12:45:02.559714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc14db5f248'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiry', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
